import re

SQL_KEYWORDS: tuple[str, ...] = (
    "select",
    "from",
    "where",
    "join",
    "with",
    "inner join",
    "left join",
    "right join",
    "full join",
    "cross join",
    "group by",
    "order by",
    "having",
    "distinct",
    "union",
    "all",
    "any",
    "exists",
    "like",
    "in",
    "between",
    "is null",
    "is not null",
    "and",
    "or",
    "not",
    "as",
    "case",
    "when",
    "then",
    "else",
    "end",
    "limit",
    "offset",
    "desc",
    "asc",
)
MONGO_KEYWORDS: tuple[str, ...] = (
    "$eq",
    "$ne",
    "$gt",
    "$gte",
    "$lt",
    "$lte",
    "$in",
    "$nin",
    "$and",
    "$or",
    "$not",
    "$exists",
    "$type",
    "$regex",
    "$where",
)
SQL_PATTERN = r"\b(" + "|".join(map(re.escape, SQL_KEYWORDS)) + r")\b"
MONGO_PATTERN = r"(?<!\w)(" + "|".join(map(re.escape, MONGO_KEYWORDS)) + r")(?!\w)"
